wandb_version: 1

batch_norm:
  value: true
batch_size:
  value: 256
conv_activation:
  value: relu
data_aug:
  value: false
dense_activation:
  value: relu
dense_size:
  value: 256
dropout:
  value: 0.2
filter_org:
  value: same
filter_size:
  value:
  - 7
  - 7
  - 7
  - 7
  - 7
in_dims:
  value: 256
learning_rate:
  value: 0.0001
n_epochs:
  value: 10
n_filters:
  value: 256
weight_decay:
  value: 0
