wandb_version: 1

batch_norm:
  value: true
batch_size:
  value: 128
conv_activation:
  value: mish
data_aug:
  value: true
dense_activation:
  value: relu
dense_size:
  value: 256
dropout:
  value: 0.2
filter_org:
  value: same
filter_size:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
in_dims:
  value: 256
learning_rate:
  value: 0.001
n_epochs:
  value: 20
n_filters:
  value: 64
weight_decay:
  value: 0
