wandb_version: 1

batch_norm:
  value: true
batch_size:
  value: 64
conv_activation:
  value: gelu
data_aug:
  value: true
dense_activation:
  value: relu
dense_size:
  value: 1024
dropout:
  value: 0.3
filter_org:
  value: double
filter_size:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
in_dims:
  value: 256
learning_rate:
  value: 0.001
n_epochs:
  value: 15
n_filters:
  value: 128
weight_decay:
  value: 0.5
