wandb_version: 1

batch_norm:
  value: false
batch_size:
  value: 128
conv_activation:
  value: silu
data_aug:
  value: true
dense_activation:
  value: relu
dense_size:
  value: 512
dropout:
  value: 0.2
filter_org:
  value: same
filter_size:
  value:
  - 7
  - 7
  - 7
  - 7
  - 7
in_dims:
  value: 256
learning_rate:
  value: 0.0001
n_epochs:
  value: 15
n_filters:
  value: 32
weight_decay:
  value: 0
