wandb_version: 1

batch_norm:
  value: true
batch_size:
  value: 128
conv_activation:
  value: mish
data_aug:
  value: false
dense_activation:
  value: relu
dense_size:
  value: 1024
dropout:
  value: 0.2
filter_org:
  value: double
filter_size:
  value:
  - 3
  - 3
  - 5
  - 5
  - 7
in_dims:
  value: 256
learning_rate:
  value: 0.0001
n_epochs:
  value: 15
n_filters:
  value: 64
weight_decay:
  value: 0
