wandb_version: 1

batch_norm:
  value: false
batch_size:
  value: 128
conv_activation:
  value: relu
data_aug:
  value: true
dense_activation:
  value: relu
dense_size:
  value: 512
dropout:
  value: 0.3
filter_org:
  value: double
filter_size:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
in_dims:
  value: 256
learning_rate:
  value: 0.001
n_epochs:
  value: 10
n_filters:
  value: 32
weight_decay:
  value: 0.005
