wandb_version: 1

batch_norm:
  value: false
batch_size:
  value: 64
conv_activation:
  value: gelu
data_aug:
  value: false
dense_activation:
  value: relu
dense_size:
  value: 1024
dropout:
  value: 0.3
filter_org:
  value: same
filter_size:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
in_dims:
  value: 256
learning_rate:
  value: 0.001
n_epochs:
  value: 20
n_filters:
  value: 32
weight_decay:
  value: 0.5
