wandb_version: 1

batch_norm:
  value: false
batch_size:
  value: 64
conv_activation:
  value: relu
data_aug:
  value: true
dense_activation:
  value: relu
dense_size:
  value: 1024
dropout:
  value: 0.2
filter_org:
  value: same
filter_size:
  value:
  - 3
  - 3
  - 5
  - 5
  - 7
in_dims:
  value: 256
learning_rate:
  value: 0.0001
n_epochs:
  value: 20
n_filters:
  value: 128
weight_decay:
  value: 0
