wandb_version: 1

batch_norm:
  value: true
batch_size:
  value: 64
conv_activation:
  value: silu
data_aug:
  value: false
dense_activation:
  value: relu
dense_size:
  value: 256
dropout:
  value: 0
filter_org:
  value: halve
filter_size:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
in_dims:
  value: 256
learning_rate:
  value: 0.001
n_epochs:
  value: 15
n_filters:
  value: 128
weight_decay:
  value: 0.005
