wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712456409.410966
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.8.10
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
batch_norm:
  desc: null
  value: false
batch_size:
  desc: null
  value: 64
conv_activation:
  desc: null
  value: relu
data_aug:
  desc: null
  value: false
dense_activation:
  desc: null
  value: relu
dense_size:
  desc: null
  value: 1024
dropout:
  desc: null
  value: 0.2
filter_org:
  desc: null
  value: double
filter_size:
  desc: null
  value:
  - 3
  - 3
  - 5
  - 5
  - 7
in_dims:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.0001
n_epochs:
  desc: null
  value: 10
n_filters:
  desc: null
  value: 32
weight_decay:
  desc: null
  value: 0.5
